#!/bin/bash

# Set environment variables
export AUTHENTICATION_FLOW_TYPE="USER_PASSWORD_AUTH"
export AWS_OAUTH_REDIRECT_SIGN_IN_URL="https://epilepsy.science"
export AWS_OAUTH_REDIRECT_SIGN_OUT_URL="https://epilepsy.science"
export AWS_USER_POOL_ID="us-east-1_b1NyxYcr0" #DNC
export AWS_USER_POOL_WEB_CLIENT_ID="" #DNC
export CTF_API_HOST="cdn.contentful.com"
export CTF_CDA_ACCESS_TOKEN="" 
export CTF_SPACE_ID=""
export DEPLOY_ENV="development"
export HOST="0.0.0.0"
export MAX_DOWNLOAD_SIZE="5000000000"
export NODE_ENV="development"
export NODE_OPTIONS=""
export NPM_CONFIG_PRODUCTION="false"
export PENNSIEVE_API_HOST="https://api.pennsieve.io"
export PENNSIEVE_DISCOVER_API_HOST="https://api.pennsieve.io/discover"
export PENNSIEVE_STREAMING="wss://api.pennsieve.io/streaming/discover/ts/query"
export PENNSIEVE_ZIPIT_HOST="https://api.pennsieve.io/zipit/discover"
export RECAPTCHA_SECRET_KEY="" 
export RECAPTCHA_SITE_KEY="" 
export ROOT_URL="https://epilepsy.science"
export SITE_URL="https://epilepsy.science"
export USER_POOL_ID="us-east-1_b1NyxYcr0" 
export USER_POOL_WEB_CLIENT_ID="" #DNC


echo "ENV VARIABLES SET:"
echo "AUTHENTICATION_FLOW_TYPE: " $AUTHENTICATION_FLOW_TYPE
echo "AWS_OAUTH_REDIRECT_SIGN_IN_URL: " $AWS_OAUTH_REDIRECT_SIGN_IN_URL
echo "AWS_OAUTH_REDIRECT_SIGN_OUT_URL: " $AWS_OAUTH_REDIRECT_SIGN_OUT_URL
echo "AWS_USER_POOL_ID: " $AWS_USER_POOL_ID
echo "AWS_USER_POOL_WEB_CLIENT_ID: " $AWS_USER_POOL_WEB_CLIENT_ID
echo "CTF_API_HOST: " $CTF_API_HOST
echo "CTF_CDA_ACCESS_TOKEN: " $CTF_CDA_ACCESS_TOKEN
echo "CTF_SPACE_ID: " $CTF_SPACE_ID
echo "DEPLOY_ENV: " $DEPLOY_ENV
echo "HOST: " $HOST
echo "MAX_DOWNLOAD_SIZE: " $MAX_DOWNLOAD_SIZE
echo "NODE_ENV: " $NODE_ENV
echo "NODE_OPTIONS: " $NODE_OPTIONS
echo "NPM_CONFIG_PRODUCTION: " $NPM_CONFIG_PRODUCTION
echo "PENNSIEVE_API_HOST: " $PENNSIEVE_API_HOST
echo "PENNSIEVE_DISCOVER_API_HOST: " $PENNSIEVE_DISCOVER_API_HOST
echo "PENNSIEVE_STREAMING: " $PENNSIEVE_STREAMING
echo "PENNSIEVE_ZIPIT_HOST: " $PENNSIEVE_ZIPIT_HOST
echo "RECAPTCHA_SECRET_KEY: " $RECAPTCHA_SECRET_KEY
echo "RECAPTCHA_SITE_KEY: " $RECAPTCHA_SITE_KEY
echo "ROOT_URL: " $ROOT_URL
echo "SITE_URL: " $SITE_URL
echo "USER_POOL_ID: " $USER_POOL_ID
echo "USER_POOL_WEB_CLIENT_ID: " $USER_POOL_WEB_CLIENT_ID